"use client";
import { useEffect, useState } from "react";
type Asset = { appearanceKey:string; thumbnailUrl:string; genderPresentation:string; bodyType:string; skinTone:string; hairTexture:string; hairStyle:string; hairColor:string; version:string; status:string; sourceType:string; qualityScore:number };
export function StudioModelAssetAdmin() {
  const [assets,setAssets]=useState<Asset[]>([]),[status,setStatus]=useState(""),[search,setSearch]=useState("");
  async function load(){const query=new URLSearchParams();if(status)query.set("status",status);if(search)query.set("appearanceKey",search);const response=await fetch(`/api/admin/studio-model-assets?${query}`,{cache:"no-store"});const json=await response.json();setAssets(json.data?.assets||[]);}
  useEffect(()=>{void load();},[status]);
  async function act(asset:Asset,action:string){if(!window.confirm(`Confirm ${action.replaceAll("_"," ")} for ${asset.appearanceKey}?`))return;await fetch("/api/admin/studio-model-assets",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({appearanceKey:asset.appearanceKey,version:asset.version,action})});await load();}
  return <main className="mx-auto max-w-6xl space-y-5 p-5"><h1 className="text-3xl font-bold">Studio Model assets</h1><div className="flex gap-2"><input className="min-h-11 flex-1 rounded-xl border px-3" value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Appearance key"/><select className="rounded-xl border px-3" value={status} onChange={(e)=>setStatus(e.target.value)}><option value="">All statuses</option>{["READY","GENERATING","MISSING","FAILED","REVIEW_REQUIRED"].map(x=><option key={x}>{x}</option>)}</select><button className="rounded-xl bg-black px-4 text-white" onClick={()=>void load()}>Search</button></div><div className="grid gap-4 md:grid-cols-2">{assets.map((asset)=><article key={`${asset.appearanceKey}:${asset.version}`} className="rounded-2xl border p-4">{asset.thumbnailUrl?<img src={asset.thumbnailUrl} alt="Studio Model candidate" className="mb-3 aspect-[3/4] h-56 rounded-xl object-contain"/>:null}<p className="break-all text-xs">{asset.appearanceKey}</p><p className="font-bold">{asset.status} · {Math.round(asset.qualityScore*100)}%</p><p className="text-sm">{asset.genderPresentation}, {asset.bodyType}, {asset.skinTone}, {asset.hairTexture}, {asset.hairStyle}, {asset.hairColor}</p><p className="text-xs">{asset.sourceType} · {asset.version}</p><div className="mt-3 flex flex-wrap gap-2">{asset.status==="REVIEW_REQUIRED"?<><button onClick={()=>void act(asset,"mark_ready")}>Approve</button><button onClick={()=>void act(asset,"reject")}>Reject</button></>:null}{asset.status==="FAILED"?<button onClick={()=>void act(asset,"requeue")}>Retry</button>:null}<button onClick={()=>void act(asset,"deprecate")}>Deprecate</button></div></article>)}</div></main>;
}
