import assert from "node:assert/strict";
import { STUDIO_MODEL_APPEARANCE_VERSION } from "../lib/studio-model/appearance-taxonomy";
import { studioModelAppearanceKey } from "../lib/studio-model/configuration";
import { selectBestStudioModelFallback } from "../lib/studio-model/catalog/asset-selection";
import { canTransitionAssetStatus } from "../lib/studio-model/catalog/asset-status";
import { STUDIO_MODEL_CATALOG_VERSION } from "../lib/studio-model/catalog/asset-version";
import { validateAssetRegistration } from "../lib/studio-model/catalog/asset-registration";
import { legacyStudioModelSeedRecords } from "../lib/studio-model/catalog/legacy-assets";

const appearance = { version: STUDIO_MODEL_APPEARANCE_VERSION, representation: "studio_model", gender: "female", bodyType: "standard", skinTone: "tone_08", hairTexture: "coily", hairLength: "long", hairColor: "black", hairStyle: "locs" } as const;
assert.equal(studioModelAppearanceKey(appearance), studioModelAppearanceKey({ ...appearance }));
assert.equal(STUDIO_MODEL_CATALOG_VERSION, "v1");
const candidates = [{ id: "wrong-body", genderPresentation: "female", bodyType: "petite", skinTone: "tone_08", hairTexture: "coily", hairLength: "long", hairColor: "black", hairStyle: "locs" }, { id: "near", genderPresentation: "female", bodyType: "standard", skinTone: "tone_07", hairTexture: "coily", hairLength: "long", hairColor: "black", hairStyle: "locs" }, { id: "far", genderPresentation: "female", bodyType: "standard", skinTone: "tone_02", hairTexture: "straight", hairLength: "short", hairColor: "blonde", hairStyle: "bob" }];
assert.equal(selectBestStudioModelFallback(candidates, appearance)?.id, "near");
assert.equal(selectBestStudioModelFallback(candidates.filter((item) => item.bodyType !== "standard"), appearance), null);
assert.equal(canTransitionAssetStatus("MISSING", "GENERATING"), true);
assert.equal(canTransitionAssetStatus("READY", "GENERATING"), false);
assert.equal(validateAssetRegistration({ assetUrl: "https://assets.example/model.png", thumbnailUrl: "https://assets.example/thumb.webp", storageKey: "studio-model-assets/v1/key/model.png", hash: "a".repeat(64), qualityScore: 1 }).qualityScore, 1);
assert.throws(() => validateAssetRegistration({ assetUrl: "http://unsafe/model.png", thumbnailUrl: "https://assets.example/thumb.webp", storageKey: "other/model.png", hash: "bad", qualityScore: 2 }));
assert.equal(JSON.stringify({ appearanceKey: studioModelAppearanceKey(appearance) }).includes("skinTone"), false);
const legacy = legacyStudioModelSeedRecords("https://myfitpick.example");
assert.equal(legacy.length, 11);
assert.equal(legacy.every((asset) => asset.status === "FALLBACK"), true);
assert.equal(new Set(legacy.map((asset) => `${asset.genderPresentation}:${asset.bodyType}`)).size, 11);
assert.equal(legacy.every((asset) => asset.assetUrl.startsWith("https://myfitpick.example/models/studio/")), true);
console.log("studio model catalog tests passed");
